# Generated by Django 2.1.5 on 2019-04-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='duration',
            field=models.CharField(default='00:00', max_length=10),
        ),
    ]
