# Generated by Django 2.1.5 on 2019-04-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='00:00', max_length=10),
        ),
    ]
